[
    {
        "Name": "Payton Preslee",
        "Born": "24/2/1994",
        "Years active": "2019",
        "Birthplace": "United States",
        "Ethnicity": "Caucasian",
        "Hair color": "Black",
        "Eye color": "Blue",
        "Height": "160",
        "Weight": "57",
        "Body type": "Average",
        "Measurements": "36F-24-36",
        "Boobs": "36",
        "Hips": "24",
        "Ass": "36",
        "Total": 48,
        "Tattoos": "Yes",
        "Piercings": "Yes"
    },

    {
    "Name": "Scarlet Chase",
    "Born": "9/3/1995",
    "Years active": "2017",
    "Birthplace": "Australia",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "34-24-36",
    "Boobs": "34",
    "Hips": "24",
    "Ass": "36",
    "Total": 46,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Kali Rose",
    "Born": "16/1/1996",
    "Years active": "2016",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "167",
    "Weight": "59",
    "Body type": "Slim",
    "Measurements": "32-25-36",
    "Boobs": "32",
    "Hips": "25",
    "Ass": "36",
    "Total": 43,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},


{
    "Name": "Abby Rose",
    "Born": "21/5/1992",
    "Years active": "2024",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Green",
    "Height": "162",
    "Weight": "57",
    "Body type": "Average",
    "Measurements": "43-31-42",
    "Boobs": "43",
    "Hips": "31",
    "Ass": "42",
    "Total": 54,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Abigaiil Morris",
    "Born": "7/6/2000",
    "Years active": "2018",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Red",
    "Eye color": "Hazel",
    "Height": "180",
    "Weight": "70",
    "Body type": "Slim",
    "Measurements": "43-28-45",
    "Boobs": "43",
    "Hips": "28",
    "Ass": "45",
    "Total": 60,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Aidra Fox",
    "Born": "25/9/1995",
    "Years active": "2013",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "54",
    "Body type": "Average",
    "Measurements": "35-28-34",
    "Boobs": "35",
    "Hips": "28",
    "Ass": "34",
    "Total": 41,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Aleksa Mink",
    "Born": "28/7/2003",
    "Years active": "2024",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Blue",
    "Height": "157",
    "Weight": "73",
    "Body type": "Average",
    "Measurements": "32-28-43",
    "Boobs": "32",
    "Hips": "28",
    "Ass": "43",
    "Total": 47,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Alex Blake",
    "Born": "9/3/1998",
    "Years active": "2016",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Hazel",
    "Height": "172",
    "Weight": "57",
    "Body type": "Slim",
    "Measurements": "36-24-36",
    "Boobs": "36",
    "Hips": "24",
    "Ass": "36",
    "Total": 48,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},
{
    "Name": "Alice Otsu",
    "Born": "19/12/1993",
    "Years active": "2021",
    "Birthplace": "Japan",
    "Ethnicity": "Asian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "160",
    "Weight": "60",
    "Body type": "Average",
    "Measurements": "35-24-39",
    "Boobs": "35",
    "Hips": "24",
    "Ass": "39",
    "Total": 50,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Amber Alena",
    "Born": "15/10/1995",
    "Years active": "2016",
    "Birthplace": "United States",
    "Ethnicity": "Mixed-race",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "165",
    "Weight": "55",
    "Body type": "Average",
    "Measurements": "36-26-40",
    "Boobs": "36",
    "Hips": "26",
    "Ass": "40",
    "Total": 50,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Andi Avalon",
    "Born": "20/8/1988",
    "Years active": "2022",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "32DD-24-35",
    "Boobs": "32",
    "Hips": "24",
    "Ass": "35",
    "Total": 43,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Angel Wicky",
    "Born": "8/4/1991",
    "Years active": "2009",
    "Birthplace": "Czech Republic",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "165",
    "Weight": "66",
    "Body type": "Average",
    "Measurements": "39-27-38",
    "Boobs": "39",
    "Hips": "27",
    "Ass": "38",
    "Total": 50,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Angel Youngs",
    "Born": "15/1/2002",
    "Years active": "2020",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "167",
    "Weight": "58",
    "Body type": "Average",
    "Measurements": "32-25-35",
    "Boobs": "32",
    "Hips": "25",
    "Ass": "35",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Angela White",
    "Born": "4/3/1985",
    "Years active": "2003",
    "Birthplace": "Australia",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Blue",
    "Height": "160",
    "Weight": "68",
    "Body type": "Average",
    "Measurements": "40-28-41",
    "Boobs": "40",
    "Hips": "28",
    "Ass": "41",
    "Total": 53,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},


{
    "Name": "Angie Lynx",
    "Born": "22/1/1994",
    "Years active": "2017",
    "Birthplace": "Finland",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "149",
    "Weight": "57",
    "Body type": "Slim",
    "Measurements": "33-24-35",
    "Boobs": "33",
    "Hips": "24",
    "Ass": "35",
    "Total": 44,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Anissa Kate",
    "Born": "7/5/1987",
    "Years active": "2011",
    "Birthplace": "France",
    "Ethnicity": "Mixed-race (primarily Middle Eastern)",
    "Hair color": "Black",
    "Eye color": "Hazel",
    "Height": "162",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "36-26-35",
    "Boobs": "36",
    "Hips": "26",
    "Ass": "35",
    "Total": 45,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Anita Mist",
    "Born": "5/7/2001",
    "Years active": null,
    "Birthplace": "Spain",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": null,
    "Weight": null,
    "Body type": "Slim",
    "Measurements": null,
    "Boobs": "",
    "Hips": "",
    "Ass": "",
    "Total": 0,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Anri Okita",
    "Born": "28/10/1986",
    "Years active": "2011",
    "Birthplace": "United Kingdom",
    "Ethnicity": "Asian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "53",
    "Body type": "Average",
    "Measurements": "51-23-42",
    "Boobs": "51",
    "Hips": "23",
    "Ass": "42",
    "Total": 70,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Apra Shay",
    "Born": "16/3/2002",
    "Years active": "2024",
    "Birthplace": "Spain",
    "Ethnicity": "Caucasian",
    "Hair color": "Auburn",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": null,
    "Body type": "Average",
    "Measurements": "34-28-34",
    "Boobs": "34",
    "Hips": "28",
    "Ass": "34",
    "Total": 40,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Armani Black",
    "Born": "28/11/1992",
    "Years active": "2021",
    "Birthplace": "United States",
    "Ethnicity": "Latin",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "162",
    "Weight": "50",
    "Body type": "Slim",
    "Measurements": "38-26-38",
    "Boobs": "38",
    "Hips": "26",
    "Ass": "38",
    "Total": 50,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Avalon Mira",
    "Born": "28/1/1998",
    "Years active": "2021",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Green",
    "Height": "170",
    "Weight": "82",
    "Body type": "Chubby",
    "Measurements": "38G-32-45",
    "Boobs": "38",
    "Hips": "32",
    "Ass": "45",
    "Total": 51,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Bambi Blitz",
    "Born": "1/4/1990",
    "Years active": "2020",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Hazel",
    "Height": "160",
    "Weight": "61",
    "Body type": "Average",
    "Measurements": "34-28-40",
    "Boobs": "34",
    "Hips": "28",
    "Ass": "40",
    "Total": 46,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Celestina Blooms",
    "Born": "13/1/1999",
    "Years active": "2021",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "167",
    "Weight": "50",
    "Body type": "Slim",
    "Measurements": "34B-26-35",
    "Boobs": "34",
    "Hips": "26",
    "Ass": "35",
    "Total": 43,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Charley Atwell",
    "Born": "24/3/1986",
    "Years active": "2010",
    "Birthplace": "United Kingdom",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "170",
    "Weight": "57",
    "Body type": "Slim",
    "Measurements": "34-26-34",
    "Boobs": "34",
    "Hips": "26",
    "Ass": "34",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Cherry Gwendolyn",
    "Born": "22/5/2000",
    "Years active": null,
    "Birthplace": "United States",
    "Ethnicity": "Mixed-race (primarily Latin)",
    "Hair color": "Red",
    "Eye color": null,
    "Height": "165",
    "Weight": "64",
    "Body type": "Chubby",
    "Measurements": null,
    "Boobs": "",
    "Hips": "",
    "Ass": "",
    "Total": 0,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Chloe Surreal",
    "Born": "22/11/1998",
    "Years active": "2022",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "157",
    "Weight": "52",
    "Body type": "Average",
    "Measurements": "32F-26-36",
    "Boobs": "32",
    "Hips": "26",
    "Ass": "36",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Clanddi Jinkcego",
    "Born": "5/5/1982",
    "Years active": "2004",
    "Birthplace": "France",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Blue",
    "Height": "167",
    "Weight": "52",
    "Body type": "Average",
    "Measurements": "34F-25-34",
    "Boobs": "34",
    "Hips": "25",
    "Ass": "34",
    "Total": 43,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Codi Vore",
    "Born": "18/5/1995",
    "Years active": "2016",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "157",
    "Weight": "65",
    "Body type": "Chubby",
    "Measurements": "44-28-40",
    "Boobs": "44",
    "Hips": "28",
    "Ass": "40",
    "Total": 56,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},


{
    "Name": "Comatozze",
    "Born": "15/1/1997",
    "Years active": "2022",
    "Birthplace": "Russian Federation",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "162",
    "Weight": "59",
    "Body type": "Slim",
    "Measurements": "36-24-37",
    "Boobs": "36",
    "Hips": "24",
    "Ass": "37",
    "Total": 49,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},


{
    "Name": "Danielle Renae",
    "Born": "19/3/1988",
    "Years active": "2023",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "154",
    "Weight": "54",
    "Body type": "Average",
    "Measurements": "32-27-36",
    "Boobs": "32",
    "Hips": "27",
    "Ass": "36",
    "Total": 41,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Devil Khloe",
    "Born": "11/5/1998",
    "Years active": "2023",
    "Birthplace": "Colombia",
    "Ethnicity": "Latin",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "165",
    "Weight": "65",
    "Body type": "Average",
    "Measurements": "34-24-34",
    "Boobs": "34",
    "Hips": "24",
    "Ass": "34",
    "Total": 44,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Elizabeth Skylar",
    "Born": "30/7/1990",
    "Years active": "2023",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "170",
    "Weight": "66",
    "Body type": "Slim",
    "Measurements": "34-27-37",
    "Boobs": "34",
    "Hips": "27",
    "Ass": "37",
    "Total": 44,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Ella Hughes",
    "Born": "13/6/1995",
    "Years active": "2015",
    "Birthplace": "United Kingdom",
    "Ethnicity": "Caucasian",
    "Hair color": "Red",
    "Eye color": "Blue",
    "Height": "154",
    "Weight": "49",
    "Body type": "Slim",
    "Measurements": "32-26-33",
    "Boobs": "32",
    "Hips": "26",
    "Ass": "33",
    "Total": 39,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Esperanza Gomez",
    "Born": "18/5/1980",
    "Years active": "2009",
    "Birthplace": "Colombia",
    "Ethnicity": "Latin",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "170",
    "Weight": "57",
    "Body type": "Athletic",
    "Measurements": "36-23-36",
    "Boobs": "36",
    "Hips": "23",
    "Ass": "36",
    "Total": 49,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},


{
    "Name": "Eve Sweet",
    "Born": "8/4/1995",
    "Years active": "2019",
    "Birthplace": "Romania",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "160",
    "Weight": "53",
    "Body type": "Slim",
    "Measurements": "34-24-34",
    "Boobs": "34",
    "Hips": "24",
    "Ass": "34",
    "Total": 44,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Gal Ritchie",
    "Born": "3/5/2001",
    "Years active": "2023",
    "Birthplace": "United Kingdom",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Blue",
    "Height": "159",
    "Weight": "57",
    "Body type": "Average",
    "Measurements": "37-26-37",
    "Boobs": "37",
    "Hips": "26",
    "Ass": "37",
    "Total": 48,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},


{
    "Name": "Gia Venetia",
    "Born": "8/12/1993",
    "Years active": "2023",
    "Birthplace": "Canada",
    "Ethnicity": "Mixed-race",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "59",
    "Body type": "Slim",
    "Measurements": "36-26-37",
    "Boobs": "36",
    "Hips": "26",
    "Ass": "37",
    "Total": 47,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Gianna Dior",
    "Born": "12/5/1997",
    "Years active": "2018",
    "Birthplace": "United States",
    "Ethnicity": "Mixed-race (primarily Caucasian)",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "162",
    "Weight": "52",
    "Body type": "Slim",
    "Measurements": "32-26-34",
    "Boobs": "32",
    "Hips": "26",
    "Ass": "34",
    "Total": 40,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Gigi Sweets",
    "Born": "18/3/2000",
    "Years active": "2023",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "160",
    "Weight": "58",
    "Body type": "Average",
    "Measurements": "34F-28-34",
    "Boobs": "34",
    "Hips": "28",
    "Ass": "34",
    "Total": 40,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Hailey Rose",
    "Born": "1/3/1999",
    "Years active": "2021",
    "Birthplace": "Colombia",
    "Ethnicity": "Mixed-race",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "157",
    "Weight": "54",
    "Body type": "Average",
    "Measurements": "32-27-34",
    "Boobs": "32",
    "Hips": "27",
    "Ass": "34",
    "Total": 39,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Hitomi Tanaka",
    "Born": "18/7/1986",
    "Years active": "2007",
    "Birthplace": "Japan",
    "Ethnicity": "Asian",
    "Hair color": "Auburn",
    "Eye color": "Brown",
    "Height": "154",
    "Weight": "50",
    "Body type": "Slim",
    "Measurements": "44-23-32",
    "Boobs": "44",
    "Hips": "23",
    "Ass": "32",
    "Total": 53,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},


{
    "Name": "Jasmine Black",
    "Born": "17/11/1987",
    "Years active": "2007",
    "Birthplace": "Romania",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "165",
    "Weight": "55",
    "Body type": "Average",
    "Measurements": "40-27-36",
    "Boobs": "40",
    "Hips": "27",
    "Ass": "36",
    "Total": 49,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Jasmine Black",
    "Born": "17/11/1987",
    "Years active": "2007",
    "Birthplace": "Romania",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "165",
    "Weight": "55",
    "Body type": "Average",
    "Measurements": "40-27-36",
    "Boobs": "40",
    "Hips": "27",
    "Ass": "36",
    "Total": 49,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
},


{
    "Name": "Jolee Love",
    "Born": "4/1/1989",
    "Years active": "2017",
    "Birthplace": "Germany",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "175",
    "Weight": "55",
    "Body type": "Average",
    "Measurements": "36DD-25-39",
    "Boobs": "36",
    "Hips": "25",
    "Ass": "39",
    "Total": 50,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Jordan Pryce",
    "Born": "2/4/1986",
    "Years active": "2007",
    "Birthplace": "Russian Federation",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "165",
    "Weight": "55",
    "Body type": "Slim",
    "Measurements": "32-24-34",
    "Boobs": "32",
    "Hips": "24",
    "Ass": "34",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Julie Cash",
    "Born": "23/5/1989",
    "Years active": "2009",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "86",
    "Body type": "BBW",
    "Measurements": "41-27-54",
    "Boobs": "41",
    "Hips": "27",
    "Ass": "54",
    "Total": 68,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Juniper Ren",
    "Born": "30/1/2004",
    "Years active": "2022",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Blue",
    "Height": "157",
    "Weight": "57",
    "Body type": "Slim",
    "Measurements": "32-24-32",
    "Boobs": "32",
    "Hips": "24",
    "Ass": "32",
    "Total": 40,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Kagney Linn Karter",
    "Born": "15/2/1987",
    "Years active": "2008",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": "55",
    "Body type": "Average",
    "Measurements": "36-25-36",
    "Boobs": "36",
    "Hips": "25",
    "Ass": "36",
    "Total": 47,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Karma Rx",
    "Born": "21/1/1993",
    "Years active": "2017",
    "Birthplace": "United States",
    "Ethnicity": "Mixed-race (primarily Caucasian)",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": "50",
    "Body type": "Average",
    "Measurements": "32-24-36",
    "Boobs": "32",
    "Hips": "24",
    "Ass": "36",
    "Total": 44,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},
{
    "Name": "Katalina Kummz",
    "Born": "25/7/1990",
    "Years active": "2020",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "165",
    "Weight": "61",
    "Body type": "Average",
    "Measurements": "36F-25-38",
    "Boobs": "36",
    "Hips": "25",
    "Ass": "38",
    "Total": 49,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Katerina Hartlova",
    "Born": "19/9/1985",
    "Years active": "2005",
    "Birthplace": "Czech Republic",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "167",
    "Weight": "57",
    "Body type": "Average",
    "Measurements": "34G-26-34",
    "Boobs": "34",
    "Hips": "26",
    "Ass": "34",
    "Total": 42,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Kayley Gunner",
    "Born": "9/1/1997",
    "Years active": "2019",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": "55",
    "Body type": "Slim",
    "Measurements": "36DD-27-38",
    "Boobs": "36",
    "Hips": "27",
    "Ass": "38",
    "Total": 47,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Kira Noir",
    "Born": "16/7/1994",
    "Years active": "2014",
    "Birthplace": "United States",
    "Ethnicity": "Black",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "59",
    "Body type": "Athletic",
    "Measurements": "34-27-35",
    "Boobs": "34",
    "Hips": "27",
    "Ass": "35",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},


{
    "Name": "Kitana Montana",
    "Born": "14/1/1993",
    "Years active": "2021",
    "Birthplace": "Netherlands",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Grey",
    "Height": "152",
    "Weight": "44",
    "Body type": "Slim",
    "Measurements": "40-24-40",
    "Boobs": "40",
    "Hips": "24",
    "Ass": "40",
    "Total": 56,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Kyra Hot",
    "Born": "24/9/1993",
    "Years active": "2012",
    "Birthplace": "Hungary",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": "57",
    "Body type": "Average",
    "Measurements": "36-25-36",
    "Boobs": "36",
    "Hips": "25",
    "Ass": "36",
    "Total": 47,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Lataya Roxx",
    "Born": "22/11/1987",
    "Years active": "2009",
    "Birthplace": "Czech Republic",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Green",
    "Height": "172",
    "Weight": "64",
    "Body type": "Average",
    "Measurements": "36-25-38",
    "Boobs": "36",
    "Hips": "25",
    "Ass": "38",
    "Total": 49,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Lexi Luna",
    "Born": "14/3/1989",
    "Years active": "2016",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Hazel",
    "Height": "170",
    "Weight": "61",
    "Body type": "Average",
    "Measurements": "34-27-39",
    "Boobs": "34",
    "Hips": "27",
    "Ass": "39",
    "Total": 46,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Lilibet",
    "Born": "21/8/2006",
    "Years active": "2025",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "154",
    "Weight": "59",
    "Body type": "Chubby",
    "Measurements": "36-29-36",
    "Boobs": "36",
    "Hips": "29",
    "Ass": "36",
    "Total": 43,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},


{
    "Name": "Lily Lou",
    "Born": "8/9/1997",
    "Years active": "2019",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "154",
    "Weight": "57",
    "Body type": "Average",
    "Measurements": "32H-25-38",
    "Boobs": "32",
    "Hips": "25",
    "Ass": "38",
    "Total": 45,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},

{
    "Name": "Lily Starfire",
    "Born": "9/8/2001",
    "Years active": "2022",
    "Birthplace": "United States",
    "Ethnicity": "Black",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "154",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "34DD-24-36",
    "Boobs": "34",
    "Hips": "24",
    "Ass": "36",
    "Total": 46,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Lissa Aires",
    "Born": "19/2/1991",
    "Years active": "2015",
    "Birthplace": "Argentina",
    "Ethnicity": "Latin",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "165",
    "Weight": "71",
    "Body type": "Chubby",
    "Measurements": "42-27-50",
    "Boobs": "42",
    "Hips": "27",
    "Ass": "50",
    "Total": 65,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Little Puck",
    "Born": "18/12/1988",
    "Years active": "2019",
    "Birthplace": "United States",
    "Ethnicity": "Latin",
    "Hair color": "Brown",
    "Eye color": "Hazel",
    "Height": "170",
    "Weight": "67",
    "Body type": "Average",
    "Measurements": "36F-29-40",
    "Boobs": "36",
    "Hips": "29",
    "Ass": "40",
    "Total": 47,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Liya Silver",
    "Born": "25/2/1999",
    "Years active": "2018",
    "Birthplace": "Kyrgyzstan",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "162",
    "Weight": "50",
    "Body type": "Slim",
    "Measurements": "36-24-32",
    "Boobs": "36",
    "Hips": "24",
    "Ass": "32",
    "Total": 44,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},

{
    "Name": "Lola Pearl",
    "Born": "1/1/1990",
    "Years active": "2017",
    "Birthplace": "United States",
    "Ethnicity": "Mixed-race (primarily Latin)",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "177",
    "Weight": "59",
    "Body type": "Slim",
    "Measurements": "34-26-36",
    "Boobs": "34",
    "Hips": "26",
    "Ass": "36",
    "Total": 44,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Lolliepopxxx",
    "Born": "22/4/1990",
    "Years active": "2024",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Grey",
    "Height": "160",
    "Weight": "58",
    "Body type": "Average",
    "Measurements": "38-28-38",
    "Boobs": "38",
    "Hips": "28",
    "Ass": "38",
    "Total": 48,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Lucia Rossi",
    "Born": "19/7/1998",
    "Years active": "2024",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Red",
    "Eye color": "Green",
    "Height": "154",
    "Weight": "54",
    "Body type": "Athletic",
    "Measurements": "32-27-37",
    "Boobs": "32",
    "Hips": "27",
    "Ass": "37",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Lucie Wilde",
    "Born": "11/1/1996",
    "Years active": "2014",
    "Birthplace": "Czech Republic",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Hazel",
    "Height": "167",
    "Weight": "56",
    "Body type": "Slim",
    "Measurements": "40-26-37",
    "Boobs": "40",
    "Hips": "26",
    "Ass": "37",
    "Total": 51,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Lucy Li",
    "Born": "4/1/1994",
    "Years active": "2013",
    "Birthplace": "Germany",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Blue",
    "Height": "167",
    "Weight": "55",
    "Body type": "Slim",
    "Measurements": "36-25-33",
    "Boobs": "36",
    "Hips": "25",
    "Ass": "33",
    "Total": 44,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Luna Star",
    "Born": "25/5/1989",
    "Years active": "2012",
    "Birthplace": "Cuba",
    "Ethnicity": "Latin",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "162",
    "Weight": "51",
    "Body type": "Slim",
    "Measurements": "32-25-35",
    "Boobs": "32",
    "Hips": "25",
    "Ass": "35",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},
{
    "Name": "Madalina Moon",
    "Born": "12/3/2002",
    "Years active": "2024",
    "Birthplace": "United States",
    "Ethnicity": "Mixed-race (primarily Latin)",
    "Hair color": "Black",
    "Eye color": "Green",
    "Height": "162",
    "Weight": "61",
    "Body type": "Average",
    "Measurements": "32-29-37",
    "Boobs": "32",
    "Hips": "29",
    "Ass": "37",
    "Total": 40,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Madison Wilde",
    "Born": "4/10/2000",
    "Years active": "2022",
    "Birthplace": "United States",
    "Ethnicity": "Latin",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "157",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "32-24-35",
    "Boobs": "32",
    "Hips": "24",
    "Ass": "35",
    "Total": 43,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Mallory Brookes",
    "Born": "11/11/2006",
    "Years active": "2025",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Hazel",
    "Height": "149",
    "Weight": null,
    "Body type": "Average",
    "Measurements": null,
    "Boobs": "",
    "Hips": "",
    "Ass": "",
    "Total": 0,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Marcieli Koltermann",
    "Born": "4/12/1979",
    "Years active": "2020",
    "Birthplace": "Brazil",
    "Ethnicity": "Latin",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": null,
    "Weight": null,
    "Body type": "Average",
    "Measurements": null,
    "Boobs": "",
    "Hips": "",
    "Ass": "",
    "Total": 0,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
},
{
    "Name": "Marica Chanel",
    "Born": "13/9/1995",
    "Years active": "2018",
    "Birthplace": "Italy",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "169",
    "Weight": "60",
    "Body type": "Average",
    "Measurements": "34-29-35",
    "Boobs": "34",
    "Hips": "29",
    "Ass": "35",
    "Total": 40,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},
{
    "Name": "Marina Visconti",
    "Born": "30/3/1995",
    "Years active": "2013",
    "Birthplace": "Russian Federation",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Blue",
    "Height": "160",
    "Weight": "58",
    "Body type": "Average",
    "Measurements": "34-26-38",
    "Boobs": "34",
    "Hips": "26",
    "Ass": "38",
    "Total": 46,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
},
{
    "Name": "Melony Melons",
    "Born": "18/2/1970",
    "Years active": "2021",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "162",
    "Weight": "69",
    "Body type": "Chubby",
    "Measurements": "36J-30-39",
    "Boobs": "36",
    "Hips": "30",
    "Ass": "39",
    "Total": 45,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
}
,{
    "Name": "Mia Molotov",
    "Born": "15/11/1999",
    "Years active": "2021",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "177",
    "Weight": "64",
    "Body type": "Average",
    "Measurements": "32-24-35",
    "Boobs": "32",
    "Hips": "24",
    "Ass": "35",
    "Total": 43,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
}
,{
    "Name": "Michu Wars",
    "Born": "31/3/1990",
    "Years active": null,
    "Birthplace": "Spain",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "159",
    "Weight": null,
    "Body type": "Slim",
    "Measurements": null,
    "Boobs": "",
    "Hips": "",
    "Ass": "",
    "Total": 0,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Mion Hazuki",
    "Born": "24/10/1990",
    "Years active": "2014",
    "Birthplace": "Japan",
    "Ethnicity": "Asian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "154",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "30J-24-36",
    "Boobs": "30",
    "Hips": "24",
    "Ass": "36",
    "Total": 42,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Nadia Goher",
    "Born": "19/10/1993",
    "Years active": null,
    "Birthplace": "United States",
    "Ethnicity": "Middle Eastern",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "152",
    "Weight": null,
    "Body type": "Average",
    "Measurements": null,
    "Boobs": "",
    "Hips": "",
    "Ass": "",
    "Total": 0,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Natalia Starr",
    "Born": "22/3/1993",
    "Years active": "2012",
    "Birthplace": "Poland",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "167",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": null,
    "Boobs": "",
    "Hips": "",
    "Ass": "",
    "Total": 0,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Nichole Saphir",
    "Born": "1/11/1996",
    "Years active": "2023",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "154",
    "Weight": null,
    "Body type": "Average",
    "Measurements": "32B-27-35",
    "Boobs": "32",
    "Hips": "27",
    "Ass": "35",
    "Total": 40,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Nika Venom",
    "Born": "3/2/1996",
    "Years active": "2019",
    "Birthplace": "United States",
    "Ethnicity": "Latin",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "162",
    "Weight": "64",
    "Body type": "Average",
    "Measurements": "36-27-39",
    "Boobs": "36",
    "Hips": "27",
    "Ass": "39",
    "Total": 48,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Pamela Blond",
    "Born": "8/6/1991",
    "Years active": "2012",
    "Birthplace": "Hungary",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "56",
    "Body type": "Slim",
    "Measurements": "32-25-39",
    "Boobs": "32",
    "Hips": "25",
    "Ass": "39",
    "Total": 46,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Rachael Cavalli",
    "Born": "8/7/1984",
    "Years active": "2015",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "175",
    "Weight": "72",
    "Body type": "Average",
    "Measurements": "36DD-29-34",
    "Boobs": "36",
    "Hips": "29",
    "Ass": "34",
    "Total": 41,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}


,{
    "Name": "Raven Hart",
    "Born": "3/5/1977",
    "Years active": "2016",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": "58",
    "Body type": "Average",
    "Measurements": "36E-27-36",
    "Boobs": "36",
    "Hips": "27",
    "Ass": "36",
    "Total": 45,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}
,{
    "Name": "Rebecca Black",
    "Born": "1/11/1996",
    "Years active": "2015",
    "Birthplace": "Czech Republic",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "53",
    "Body type": "Slim",
    "Measurements": "32-24-34",
    "Boobs": "32",
    "Hips": "24",
    "Ass": "34",
    "Total": 42,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}
,{
    "Name": "Rebel Rhyder",
    "Born": "24/1/1994",
    "Years active": "2019",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "160",
    "Weight": "59",
    "Body type": "Slim",
    "Measurements": "34-24-35",
    "Boobs": "34",
    "Hips": "24",
    "Ass": "35",
    "Total": 45,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}
,{
    "Name": "Rei Sky",
    "Born": "20/9/1994",
    "Years active": "2024",
    "Birthplace": "Colombia",
    "Ethnicity": "Mixed-race (primarily Asian)",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "59",
    "Body type": "Average",
    "Measurements": "36-",
    "Boobs": "",
    "Hips": "",
    "Ass": "",
    "Total": 0,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}
,{
    "Name": "Reyna Belle",
    "Born": "4/8/2003",
    "Years active": "2023",
    "Birthplace": "United States",
    "Ethnicity": "Latin",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "157",
    "Weight": "57",
    "Body type": "Average",
    "Measurements": "36F-26-33",
    "Boobs": "36",
    "Hips": "26",
    "Ass": "33",
    "Total": 43,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}
,{
    "Name": "Rissa May",
    "Born": "14/1/2005",
    "Years active": "2023",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Auburn",
    "Eye color": "Brown",
    "Height": "162",
    "Weight": "57",
    "Body type": "Slim",
    "Measurements": "32DD-22-32",
    "Boobs": "32",
    "Hips": "22",
    "Ass": "32",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Roxanne Roselle",
    "Born": "13/7/1997",
    "Years active": "2024",
    "Birthplace": "United States",
    "Ethnicity": "Latin",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "170",
    "Weight": "64",
    "Body type": "Average",
    "Measurements": "36-31-51",
    "Boobs": "36",
    "Hips": "31",
    "Ass": "51",
    "Total": 56,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Roxie Sinner",
    "Born": "20/12/2000",
    "Years active": "2018",
    "Birthplace": "Syrian Arab Republic",
    "Ethnicity": "Middle Eastern",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "167",
    "Weight": "64",
    "Body type": "Athletic",
    "Measurements": "34-25-36",
    "Boobs": "34",
    "Hips": "25",
    "Ass": "36",
    "Total": 45,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Ryan Keely",
    "Born": "2/7/1984",
    "Years active": "2006",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "175",
    "Weight": "70",
    "Body type": "Average",
    "Measurements": "38-26-38",
    "Boobs": "38",
    "Hips": "26",
    "Ass": "38",
    "Total": 50,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Shione Cooper",
    "Born": "1/6/1987",
    "Years active": "2008",
    "Birthplace": "Czech Republic",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Green",
    "Height": "172",
    "Weight": "61",
    "Body type": "Average",
    "Measurements": "34-28-36",
    "Boobs": "34",
    "Hips": "28",
    "Ass": "36",
    "Total": 42,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Sinatra Monroe",
    "Born": "20/6/1996",
    "Years active": "2023",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Red",
    "Eye color": "Hazel",
    "Height": "162",
    "Weight": "61",
    "Body type": "Athletic",
    "Measurements": "34-26-38",
    "Boobs": "34",
    "Hips": "26",
    "Ass": "38",
    "Total": 46,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}
,{
    "Name": "Skylar Vox",
    "Born": "9/1/2000",
    "Years active": "2019",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "160",
    "Weight": "59",
    "Body type": "Average",
    "Measurements": "37-25-35",
    "Boobs": "37",
    "Hips": "25",
    "Ass": "35",
    "Total": 47,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Sophie Reade",
    "Born": "18/5/1989",
    "Years active": "2005",
    "Birthplace": "United Kingdom",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "167",
    "Weight": "58",
    "Body type": "Average",
    "Measurements": "38-26-37",
    "Boobs": "38",
    "Hips": "26",
    "Ass": "37",
    "Total": 49,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Summer Renee",
    "Born": "22/6/2001",
    "Years active": "2025",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Brown",
    "Eye color": "Brown",
    "Height": "147",
    "Weight": "45",
    "Body type": "Slim",
    "Measurements": "32D-24-34",
    "Boobs": "32",
    "Hips": "24",
    "Ass": "34",
    "Total": 42,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}
,{
    "Name": "Taylor Wild",
    "Born": "17/1/1989",
    "Years active": "2021",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "170",
    "Weight": "59",
    "Body type": "Athletic",
    "Measurements": "34-25-36",
    "Boobs": "34",
    "Hips": "25",
    "Ass": "36",
    "Total": 45,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}
,{
    "Name": "Tru Kait",
    "Born": "11/9/1997",
    "Years active": "2019",
    "Birthplace": "United States",
    "Ethnicity": "Latin",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "157",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "34-25-38",
    "Boobs": "34",
    "Hips": "25",
    "Ass": "38",
    "Total": 47,
    "Tattoos": "No",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Valarie Ruvalcaba",
    "Born": "21/10/2002",
    "Years active": "2022",
    "Birthplace": "Mexico",
    "Ethnicity": "Latin",
    "Hair color": "Brown",
    "Eye color": "Hazel",
    "Height": "149",
    "Weight": "57",
    "Body type": "Chubby",
    "Measurements": "34-27-39",
    "Boobs": "34",
    "Hips": "27",
    "Ass": "39",
    "Total": 46,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}


,{
    "Name": "Viola Bailey",
    "Born": "3/3/1993",
    "Years active": "2013",
    "Birthplace": "Latvia",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "162",
    "Weight": "55",
    "Body type": "Slim",
    "Measurements": "34-25-36",
    "Boobs": "34",
    "Hips": "25",
    "Ass": "36",
    "Total": 45,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Yasmina Khan",
    "Born": "27/3/1997",
    "Years active": "2019",
    "Birthplace": "Bangladesh",
    "Ethnicity": "Asian",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "157",
    "Weight": "57",
    "Body type": "Average",
    "Measurements": "33FF-26-35",
    "Boobs": "33",
    "Hips": "26",
    "Ass": "35",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}

,{
    "Name": "Lucette Nice",
    "Born": "7/10/1997",
    "Years active": "2017",
    "Birthplace": "Hungary",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "167",
    "Weight": "52",
    "Body type": "Slim",
    "Measurements": "34DD-24-32",
    "Boobs": "34",
    "Hips": "24",
    "Ass": "32",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Carina Blair",
    "Born": "15/6/1992",
    "Years active": "2022",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Blue",
    "Height": "157",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "36-26-35",
    "Boobs": "36",
    "Hips": "26",
    "Ass": "35",
    "Total": 45,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}


,{
    "Name": "Jade Valentine",
    "Born": "13/1/1997",
    "Years active": "2022",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Blue",
    "Height": "162",
    "Weight": "59",
    "Body type": "Slim",
    "Measurements": "35B-26-39",
    "Boobs": "35",
    "Hips": "26",
    "Ass": "39",
    "Total": 48,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}

,{
    "Name": "Madelynn May",
    "Born": "22/2/1993",
    "Years active": "2017",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Blonde",
    "Eye color": "Green",
    "Height": "149",
    "Weight": "62",
    "Body type": "Average",
    "Measurements": "34-27-35",
    "Boobs": "34",
    "Hips": "27",
    "Ass": "35",
    "Total": 42,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}


,{
    "Name": "Lacey Jayne",
    "Born": "7/1/1995",
    "Years active": "2020",
    "Birthplace": "United States",
    "Ethnicity": "Caucasian",
    "Hair color": "Black",
    "Eye color": "Green",
    "Height": "160",
    "Weight": null,
    "Body type": "Average",
    "Measurements": "39-23-29",
    "Boobs": "39",
    "Hips": "23",
    "Ass": "29",
    "Total": 45,
    "Tattoos": "Yes",
    "Piercings": "Yes",
    "Image": ""
}


,{
    "Name": "Scarlett Alexis",
    "Born": "30/4/1999",
    "Years active": "2022",
    "Birthplace": "United States",
    "Ethnicity": "Latin",
    "Hair color": "Black",
    "Eye color": "Brown",
    "Height": "165",
    "Weight": "54",
    "Body type": "Slim",
    "Measurements": "34DD-26-36",
    "Boobs": "34",
    "Hips": "26",
    "Ass": "36",
    "Total": 44,
    "Tattoos": "No",
    "Piercings": "No",
    "Image": ""
}


,{
    "Name": "Ava Amira",
    "Born": "10/11/1993",
    "Years active": "2020",
    "Birthplace": "Iraq",
    "Ethnicity": "Mixed-race (primarily Middle Eastern)",
    "Hair color": "Blonde",
    "Eye color": "Brown",
    "Height": "162",
    "Weight": "50",
    "Body type": null,
    "Measurements": "34-23-34",
    "Boobs": "34",
    "Hips": "23",
    "Ass": "34",
    "Total": 45,
    "Tattoos": "Yes",
    "Piercings": "No",
    "Image": ""
}












]
